blank_issues_enabled: false
contact_links:
  - name: Aevoa Studios Technical Support
    url: https://aevoa.tech/
    about: Please create a ticket here if you need help with the platform
  - name: Novo Networks Community Discord
    url: https://discord.gg/rqaz9xfB
    about: For any other questions